environment:
    global:
        PYTHON: "C:\\conda"
        MINICONDA_VERSION: "latest"
        CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
        PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                          # of 32 bit and 64 bit builds are needed, move this
                          # to the matrix section.
        CONDA_DEPENDENCIES: "Cython scipy numpy scikit-image"

    matrix:
        - PYTHON_VERSION: "3.5"
          NUMPY_VERSION: "stable"
        - PYTHON_VERSION: "3.6"
          NUMPY_VERSION: "stable"

matrix:
    fast_finish: true

platform:
    -x64

install:
    - "git clone --depth 1 git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"
    - "%CMD_IN_ENV% pip install -r requirements.txt"
    - "%CMD_IN_ENV% pip install git+https://github.com/dvolgyes/TMQI"

build: off

test_script:
  - wintest.bat
